---

- name: Crear db
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ db }}"
  become: true
  become_method: su
  become_user: postgres


- name: Crear usuarios
  community.postgresql.postgresql_user:
    name: "{{ item.nombre }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role_attr }}"
  with_items: "{{ info_usuarios }}"
  become: true
  become_method: su
  become_user: postgres

...
