---

- name: Descargar, descomprimir Wordpress
  ansible.builtin.unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: true
    mode: '0775'
    owner: www-data
    group: www-data
  notify: Reinciar http/apache2

- name: Configuracion wp-config
  ansible.builtin.include_tasks: wp-config.yml
  notify: Reiniciar httpd/apache2

...
