---

- name: Descargar, descomprimir Wordpress
  ansible.builtin.unarchive:
    src: https://es.wordpress.org/wordpress-5.1.6-es_ES.tar.gz
    dest: /var/www/html/
    remote_src: true
    mode: '0775'
    owner: www-data
    group: www-data
  notify: Reiniciar apache2
  when: ansible_distribution == "Debian"


- name: Descargar, descomprimir Wordpress
  ansible.builtin.unarchive:
    src: https://es.wordpress.org/wordpress-5.1.6-es_ES.tar.gz
    dest: /var/www/html/
    remote_src: true
    mode: '0775'
    owner: apache
    group: apache
  notify: Reiniciar httpd
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"


- name: Configuracion wp-config
  ansible.builtin.include_tasks:
    file: pg4wp.yml


- name: Configuracion wp-config
  ansible.builtin.include_tasks:
    file: wp-config.yml

...
