---

- name: Comprobar si existe el fichero wp-config.php
  ansible.builtin.stat:
    path: /var/www/html/wordpress/wp-config.php
  register: fichero_config


- name: Comprobar si existe el fichero wp-config-sample.php
  ansible.builtin.stat:
    path: /var/www/html/wordpress/wp-config-sample.php
  register: fichero_ejemplo
  when: fichero_config.stat.exists == false


- name: Crear fichero de configuracion utilizando el fichero de ejemplo
  ansible.builtin.copy:
    src: /var/www/html/wordpress/wp-config-sample.php
    dest: /var/www/html/wordpress/wp-config.php
    mode: '0775'
    remote_src: true
  when: fichero_config.stat.exists == false


- name: Modificamos la linea de nombre de db para la conexion con la base de datos
  ansible.builtin.lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    line: "define( 'DB_NAME', '{{ db_name }}' );"
    search_string: "define( 'DB_NAME', 'database_name_here' );"
    state: present


- name: Modificamos la linea de usuario para la conexion con la base de datos
  ansible.builtin.lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    line: "define( 'DB_USER', '{{ db_user }}' );"
    search_string: "define( 'DB_USER', 'username_here' );"
    state: present


- name: Modificamos la linea de passord para la conexion con la base de datos
  ansible.builtin.lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    line: "define( 'DB_PASSWORD', '{{ db_password }}' );"
    search_string: "define( 'DB_PASSWORD', 'password_here' );"
    state: present

- name: Añadir linea de puerto para la conexion con la base de datos
  ansible.builtin.lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    line: define('DB_PORT', '5432');
    state: present

- name: Añadir linea de puerto para la conexion con la base de datos
  ansible.builtin.lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    line: define('DB_TYPE', 'pgsql');
    state: present

...
