---

- name: Reiniciar httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "8"


- name: Reiniciar apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Debian"

...
