---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Stat de la carpeta /var/www/wordpress
      stat:
        path: /var/www/html/wordpress
      register: wordpress
 
    - name: Comprobar que existe la carpeta /var/www/wordpress
      assert:
        that: wordpress.stat.exists == true
        success_msg: "Wordpress instalado"
        fail_msg: "Wordpress NO estainstalado"
 
    - name: Stat de la carpeta /usr/bin/php
      stat:
        path: /usr/bin/php
      register: php

    - name: Comprobar que existe la carpeta /usr/bin/php
      assert:
        that: php.stat.exists == true
        success_msg: "PHP instalado"
        fail_msg: "PHP NO estainstalado"
